# Generated by Django 3.1.1 on 2021-02-15 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210211_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='creditamount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
