# Generated by Django 3.1.1 on 2021-03-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210214_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='creditpaymentpackage',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CreditPaymentPackage',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
