# Generated by Django 3.1.1 on 2020-10-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_delete_gamepicked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='favorite',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='line',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='loser',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='loserscore',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='playerpick',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='scoredifferential',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='underdog',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='winnerscore',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
