# Generated by Django 3.1.1 on 2020-10-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20201006_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='line',
            field=models.FloatField(blank=True, default=''),
        ),
    ]
