# Generated by Django 3.1.1 on 2020-10-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20201006_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='line',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='game',
            name='loserscore',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='scoredifferential',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='winnerscore',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
