# Generated by Django 3.1.1 on 2020-10-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20201006_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='loser',
        ),
    ]
