# Generated by Django 3.1.1 on 2020-10-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_remove_game_loser'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamedate',
            field=models.CharField(default='', max_length=10),
        ),
    ]
