# Generated by Django 3.1.1 on 2020-10-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_auto_20201010_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='playerpick',
        ),
        migrations.RemoveField(
            model_name='playerpick',
            name='pickscoretoadd',
        ),
        migrations.AddField(
            model_name='playerpick',
            name='teampicked',
            field=models.CharField(default='', max_length=50),
        ),
    ]
