# Generated by Django 3.1.1 on 2020-10-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_game_teampicked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teampicked',
            field=models.CharField(blank=True, choices=[(models.CharField(blank=True, default='', max_length=50), models.CharField(blank=True, default='', max_length=50)), (models.CharField(blank=True, default='', max_length=50), models.CharField(blank=True, default='', max_length=50))], default='', max_length=50),
        ),
    ]
