# Generated by Django 3.1.1 on 2020-10-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_auto_20201015_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teampicked',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('a', 'a')], default='', max_length=50),
        ),
    ]
