# Generated by Django 3.1.1 on 2020-10-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_auto_20201015_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teampicked',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
