# Generated by Django 3.1.1 on 2020-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_auto_20201015_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
