# Generated by Django 3.1.1 on 2020-11-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_auto_20201125_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='gamedate',
        ),
    ]
