# Generated by Django 3.1.1 on 2020-11-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_auto_20201125_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='startdate',
            field=models.CharField(default='Wednesday', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.CharField(default='Wednesday', max_length=20),
        ),
    ]
