# Generated by Django 3.1.1 on 2020-11-25 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_auto_20201125_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default=datetime.datetime(2020, 11, 25, 19, 15, 5, 911787, tzinfo=utc), max_length=20, verbose_name='Group start date'),
        ),
    ]
