# Generated by Django 3.1.1 on 2020-11-25 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_auto_20201125_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default=datetime.datetime(2020, 11, 25, 19, 18, 27, 780439, tzinfo=utc), max_length=20, verbose_name='Group start date'),
        ),
    ]
