# Generated by Django 3.1.1 on 2020-11-25 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0023_auto_20201125_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default=datetime.datetime(2020, 11, 25, 23, 45, 1, 388091, tzinfo=utc), max_length=20, verbose_name='Group start date'),
        ),
    ]
