# Generated by Django 3.1.1 on 2020-12-21 18:54

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_auto_20201125_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpick',
            name='timemade',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.CharField(default='Monday', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default=datetime.datetime(2020, 12, 21, 18, 53, 53, 38477, tzinfo=utc), max_length=20, verbose_name='Group start date'),
        ),
    ]
