# Generated by Django 3.1.1 on 2020-12-21 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0025_auto_20201221_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default=datetime.datetime(2020, 12, 21, 18, 57, 6, 327765, tzinfo=utc), max_length=20, verbose_name='Group start date'),
        ),
    ]
