# Generated by Django 3.1.1 on 2020-12-21 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0027_auto_20201221_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default=datetime.datetime(2020, 12, 21, 19, 21, 6, 68242, tzinfo=utc), max_length=20, verbose_name='Group start date'),
        ),
        migrations.AlterField(
            model_name='playerpick',
            name='timemade',
            field=models.CharField(default='', max_length=30),
        ),
    ]
