# Generated by Django 3.1.1 on 2020-12-29 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0028_auto_20201221_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.CharField(default='Tuesday', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default=datetime.datetime(2020, 12, 29, 2, 24, 35, 661303, tzinfo=utc), max_length=20, verbose_name='Group start date'),
        ),
    ]
