# Generated by Django 3.1.1 on 2020-12-31 21:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0029_auto_20201229_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pickable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.CharField(default='Thursday', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default=datetime.datetime(2020, 12, 31, 21, 2, 13, 334946, tzinfo=utc), max_length=20, verbose_name='Group start date'),
        ),
    ]
