# Generated by Django 3.1.1 on 2020-12-31 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0030_auto_20201231_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default=datetime.datetime(2020, 12, 31, 21, 17, 6, 768378, tzinfo=utc), max_length=20, verbose_name='Group start date'),
        ),
    ]
