# Generated by Django 3.1.1 on 2021-01-10 22:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0031_auto_20201231_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='starttime',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.CharField(default='Sunday', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default=datetime.datetime(2021, 1, 10, 22, 7, 42, 281985, tzinfo=utc), max_length=20, verbose_name='Group start date'),
        ),
    ]
