# Generated by Django 3.1.1 on 2021-02-09 21:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0032_auto_20210110_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.CharField(default='Tuesday', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default=datetime.datetime(2021, 2, 9, 21, 39, 13, 423943, tzinfo=utc), max_length=20, verbose_name='Group start date'),
        ),
    ]
