# Generated by Django 3.1.1 on 2021-02-13 00:55

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_auto_20210213_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='paidorfree',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], default='Free', max_length=7, verbose_name='Free or Paid'),
        ),
        migrations.AlterField(
            model_name='group',
            name='cost',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default=datetime.datetime(2021, 2, 13, 0, 55, 56, 223329, tzinfo=utc), max_length=20, verbose_name='Group start date'),
        ),
    ]
