# Generated by Django 3.1.1 on 2021-02-14 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0035_auto_20210213_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pot',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(125)]),
        ),
        migrations.AddField(
            model_name='group',
            name='winner',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.CharField(default='Sunday', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Cost of Entry'),
        ),
        migrations.AlterField(
            model_name='group',
            name='numplayers',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='Max number of players'),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default='2021-02-14 16:52', max_length=30, verbose_name='Group start date'),
        ),
    ]
