# Generated by Django 3.1.1 on 2021-02-15 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0036_auto_20210214_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pot',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(125)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default='2021-02-14 19:23', max_length=30, verbose_name='Group start date'),
        ),
    ]
