# Generated by Django 3.1.1 on 2021-02-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0037_auto_20210214_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default='2021-02-14 19:47', max_length=30, verbose_name='Group start date'),
        ),
    ]
