# Generated by Django 3.1.1 on 2021-03-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0040_auto_20210228_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='payoutdate',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default='2021-02-28 23:26', max_length=30, verbose_name='Group start date'),
        ),
    ]
