# Generated by Django 3.1.1 on 2021-03-11 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0045_auto_20210311_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='length',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='numplayers',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)], verbose_name='Max number of players'),
        ),
        migrations.AlterField(
            model_name='group',
            name='ppw',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)], verbose_name='Number of picks per week'),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default='2021-03-11 21:14', max_length=30, verbose_name='Group start date'),
        ),
    ]
