# Generated by Django 3.1.1 on 2021-03-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0046_auto_20210311_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.CharField(default='Friday', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default='2021-03-12 21:09', max_length=30, verbose_name='Group start date'),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdaydate',
            field=models.CharField(default='Friday', max_length=20),
        ),
    ]
