# Generated by Django 3.1.1 on 2021-03-14 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0048_auto_20210314_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='weeksleft',
        ),
        migrations.AlterField(
            model_name='group',
            name='length',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(17)], verbose_name='How many weeks will your group run for? (1-17)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='startdate',
            field=models.CharField(default='2021-03-14 18:26', max_length=30, verbose_name='Group start date'),
        ),
    ]
